### ISSUE TITLE
No objloader

### ISSUE THREAD

**Issue by tort-dla-psa** [ak352/pycv#1]
When i try to run ar tests, i get an error:
Traceback (most recent call last):
  File "test_furn.py", line 5, in <module>
    import ar
  File "/home/essir/pycv-master/scripts/ar/ar.py", line 10, in <module>
    import objloader
ImportError: No module named objloader

**Comment by ak352** [comment]
Thanks. It is a script to load OBJ files from a pygame [webpage]: https://www.pygame.org/wiki/OBJFileLoader. I will add it soon.
